version: '3.8'

services:
  mysql:
    image: mysql:8.0.27
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=11999966
      - MYSQL_DATABASE=interview
      - MYSQL_USER=interviewuser
      - MYSQL_PASSWORD=11999966
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./migration/init.sql:/data/application/init.sql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    restart: always
    expose:
      - 9200
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536  
    volumes:
      - elastic:/usr/share/elasticsearch/data
  redis:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - cache:/var/lib/redis
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo
  app:
    depends_on:
      - mysql
      - elasticsearch
      - redis
      - mongo
    build: .
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: npm start
volumes: 
  db:
  elastic:
  cache:
  mongo: